ALGORITHM_HMAC_SHA256 = "HmacSHA256"

HEADER_NAME_APPID = "X-Signature-appid"
HEADER_NAME_TIMESTAMP = "X-Signature-timestamp"
HEADER_NAME_NONCE = "X-Signature-nonce"
HEADER_NAME_ALGORITHM = "X-Signature-algorithm"
HEADER_NAME_SIGNEDHEADERS = "X-Signature-signedHeaders"
HEADER_NAME_SIGNATURE = "X-Signature-signature"

URL_ISEXIST = "/v1/file/isExists"
URL_UPLOAD_ATTACHMENT = "/v1/file/uploadInfo"
URL_DOWNLOAD_ATTACHMENT = "/v1/file/download"
URL_DEL_ATTACHMENT = "/v1/file/delAuthorize"
URL_SEND_MSG = "/v1/messages"
URL_ACCOUNT = "/v1/accounts"